#!/usr/bin/env bash

# These should be installed everywhere
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile"
ln -sf "$PWD/.vimrc" "$HOME/.vimrc"

# Should I setup these up in all systems or only when these things are
# installed? Need a quick install setup too
#ln -sf "$PWD/.ansible.cfg" "$HOME/.ansible.cfg"
#ln -sf "$PWD/.gitconfig" "$HOME/.gitconfig"
